# Generated by Django 4.0.6 on 2022-11-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_remove_followrs_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrs',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='followrs',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
