# Generated by Django 4.0.6 on 2022-11-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_followrs_date_alter_followrs_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrs',
            name='date',
        ),
        migrations.AddField(
            model_name='followrs',
            name='number',
            field=models.IntegerField(default=2, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='followrs',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='followrs',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='followrs',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
