# Generated by Django 4.0.6 on 2022-11-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_remove_followrs_date_followrs_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrs',
            name='number',
            field=models.IntegerField(max_length=20, unique=True, verbose_name='phone'),
        ),
    ]
