# Generated by Django 4.0.6 on 2022-11-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_alter_followrs_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrs',
            name='number',
        ),
        migrations.AlterField(
            model_name='followrs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
