# Generated by Django 4.0.6 on 2022-11-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_remove_followrs_number_alter_followrs_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrs',
            name='phone',
            field=models.IntegerField(max_length=20, null=True, unique=True, verbose_name='phone'),
        ),
    ]
