# Generated by Django 4.0.6 on 2022-11-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0012_alter_followrs_email_alter_followrs_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrs',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
