# Generated by Django 4.0.6 on 2022-11-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0013_alter_followrs_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrs',
            name='phone',
        ),
        migrations.AlterField(
            model_name='followrs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
